# Synap adapter configuration
instance_id: "${SYNAP_INSTANCE_ID}"
api_key: "${SYNAP_API_KEY}"
base_url: "${SYNAP_BASE_URL}"
# mode: "ACCURATE"
mode: "FAST"
top_k: 50
default_user_id: "benchmark_user"

# gRPC settings
grpc_host: "${SYNAP_GRPC_HOST}"
grpc_port: 443
grpc_use_tls: true
